### ISSUE TITLE
make fails.

### ISSUE THREAD

**Issue by ghost** [lukaszcz/pascaladt#3]
I cannot get the package to build.  After downloading and extracting to build by:
 
   tar xcf pascaladt-1.0.2.tar.gz
   cd pascaladt-1.0.2
   make
   
the tools directory is built  with  hashtable/ , mkdeps, mktempl and mcp.

In the main directory the first few files are built, but the make fails with the message

   mcp: Fatal error: Cannot open file: adtutils.mcp\n; No such file or directory"

The file adtutils.mcp exists, with permissions: 

   -rw-r--r-- 1 lucy users  487 Aug  6 18:30 adtutils.mcp
   
That's the end of the make.

System: SuSE linux, fully patched, identifies as:
   uname -a
   Linux localhost.localdomain 5.14.21-150500.55.52-default #1 SMP PREEMPT_DYNAMIC Tue Mar 5 16:53:41 UTC 2024 (a62851f) x86_64 x86_64 x86_64 GNU/Linux

Normally make runs with -j 4; the same failure occurs with -j 1.

I will attach a complete log of the attempted build.
[make_log.txt](https://github.com/user-attachments/files/16553528/make_log.txt)

Thanks for your help

**Comment by lukaszcz** [comment]
I'm not completely sure what the cause of this error is, because I cannot reproduce it on my Linux machine. However, I suspect this is due to a slightly different behaviour of the `echo` command which is apparently not portable across different Linux systems. I changed it to `printf`.

Please check the new release v1.0.3 and let me know if it solves the problem.

**Comment by ghost** [comment]
v1.0.3 works fine. Make suceeds, all tests pass.

Difference may be between /bin/echo and the bash built-in? (That's just a guess)

Many thanks
Lucy

**Comment by lukaszcz** [comment]
> Difference may be between /bin/echo and the bash built-in? (That's just a guess)

Yes, probably that was the cause.
